// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrVBPcdEd8MoyPboAeMwzXcbN2rayBsXU',
    appId: '1:24979268019:web:946e94619fd84aa3f86bc6',
    messagingSenderId: '24979268019',
    projectId: 'rideglidefire',
    authDomain: 'rideglidefire.firebaseapp.com',
    storageBucket: 'rideglidefire.appspot.com',
    measurementId: 'G-XCKTTBKJLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYS21p1IEY-9dDDqI0BUQh5Ge4Zcz_A5I',
    appId: '1:827007324661:android:91c959ac953f13cb0cd0bc',
    messagingSenderId: '827007324661',
    projectId: 'rideapp-2fc2d',
    storageBucket: 'rideapp-2fc2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Q119ZCYt9ddX4oBWFfnr1PlBTWdBBjM',
    appId: '1:827007324661:ios:358ce7188bdcbfdb0cd0bc',
    messagingSenderId: '827007324661',
    projectId: 'rideapp-2fc2d',
    storageBucket: 'rideapp-2fc2d.appspot.com',
    iosBundleId: 'com.example.rideGlide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-mwWVmMkxm3ABdrExyI1JeChZ3N_NsmI',
    appId: '1:24979268019:ios:2fecabcef133e90af86bc6',
    messagingSenderId: '24979268019',
    projectId: 'rideglidefire',
    storageBucket: 'rideglidefire.appspot.com',
    iosClientId:
        '24979268019-6q83l5r0hbtg6l8drcknvq40hmp2t7q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideGlide.RunnerTests',
  );
}